authentication/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = "users"

urlpatterns = [
    path('', views.HomeView.as_view(), name='HomeView'),
    path('register/', views.RegisterView.as_view(), name='RegisterView'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='LoginView'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='LogoutView'),
    path('profile/', views.ProfileView.as_view(), name='ProfileView'),
    path('change_password/', views.ChangePasswordView.as_view(), name='ChangePasswordView'),
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from core.utils import serve_static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
]

urlpatterns += serve_static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "ADMIN PANEL"
admin.site.site_title = "ADMIN PANEL"
admin.site.index_title = "Custom Title"

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser 
from PIL import Image
from django.conf import settings

class User(AbstractUser):
    GENDER_CHOICES = (
        (1, 'Male'),
        (2, 'Female'),
        (3, 'Other'),
    )
    image = models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/', null=True, blank=True)
    gender = models.IntegerField(choices=GENDER_CHOICES, default=1)

    def __str__(self):
        return f'{self.username}'

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    @property
    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    @property
    def get_image_url(self):
        try:
            if self.image:
                return self.image.url
            return f"{settings.MEDIA_URL}/no_image.jpg"
        except:
            return ""

authentication/forms.py
from django import forms
# from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'image',
            'gender',
            'password1',
            'password2'
        ]


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'image',
            'gender',
        ]

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .forms import UserRegisterForm, UserUpdateForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


class HomeView(View):
    def get(self, request):
        return render(request, "home.html")

class RegisterView(View):
    def get(self, request):
        form = UserRegisterForm()
        return render(request, 'users/register.html', {'form': form})

    def  post(self, request):
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('users:LoginView')
        return render(request, 'users/register.html', {'form': form})


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):

        u_form = UserUpdateForm(instance=request.user)

        context = {
            'u_form': u_form
        }

        return render(request, 'users/profile.html', context)

    def post(self, request):
        u_form = UserUpdateForm(request.POST, request.FILES, instance=request.user)

        if u_form.is_valid():
            u_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('users:ProfileView')
        context = {
            'u_form': u_form
        }
        return render(request, 'users/profile.html', context)

class ChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    template_name = "users/change_password.html"

    def get_success_url(self):
        return reverse("users:HomeView")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- SEO -->
    <meta name="description" content="CPIC Travel is the official flights and travel management system for the Christian Polytechnic Institute of Catanduanes.">
    <meta name="keywords" content="virac, CPIC, Christian Polytechnic Institute of Catanduanes, CPICTravel, cpic-travel.heroku.com, cpic-travel, travel">
    <meta name="author" content="Arnel Jan Sarmiento">
    
    <meta property="og:title" content="CPIC Travel">
    <meta property="og:description" content="CPIC Travel is the official flights and travel management system for the Christian Polytechnic Institute of Catanduanes.">
    <meta property="og:type" content="website">

    <meta name="google-site-verification" content="uGL2QJWFkQOuE4tTphFQK3T22IAkXbDjTzULH6TzbVQ" />
    <meta name="msvalidate.01" content="2751098384C18FDBDC12FB95F05B7DAF" />

    {% comment %} <link rel="icon" href="{% static '/favicon/favicon.ico' %}"> {% endcomment %}
    <link rel="icon" type="image/png" href="{% static 'images/icon.png' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/cda8e305d5.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

    <title>Django App</title>

    {% block ExtraCss %} {% endblock ExtraCss %}

</head>

<body>
    {% include 'template_parts/navbar.html' %}

    <main style="min-height: 50vh;">

        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show mx-4 my-2" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}

        {% block content %} 
        
        {% endblock content %}
    </main>

    {% include 'template_parts/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="js/index.js"></script>
    

    {% block ExtraJs %} {% endblock ExtraJs %}
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<article>
  {% comment %} Add any content here {% endcomment %}
</article>
{% endblock content %}

templates/template_parts/footer.html
{% load static %}

<section>
  <div class="footer py-5">
    <ul class="me-auto">
      <h5>NEED HELP?</h5>
      <div class="set set-border">
        <li>Call Us</li>
        <li class="bold">
          <a href="tel:0000000000" target="_blank" class="a_no_style">
            0000000000
          </a>
        </li>
      </div>

      <div class="set set-border">
        <li>Email for Us</li>
        <li class="bold">
          <a href="mailto:someone@email.com" target="_blank" class="a_no_style">
            someone@email.com
          </a>
        </li>
      </div>

      <div class="set set-border">
        <li>Follow Us</li>
        <li class="bold">
          <a href="https://www.facebook.com/Christian-Polytechnic-Institute-of-Catanduanes-272035306147141" target="_blank" class="a_no_style me-2" rel="noreferrer">
            <i class="fa-brands fa-facebook-f"></i>
          </a>
        </li>
      </div>
    </ul>
  </div>
</section>

templates/template_parts/navbar.html
{% load static %}

<nav class="main__navbar navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'users:HomeView' %}">
        Auth
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav my-2 my-lg-0 navbar-nav-scroll">

          <a class="nav-link" href="#">
            Custom
          </a>

        </ul>

        {% if request.user.is_authenticated %}
          <ul class="navbar-nav my-2 my-lg-0 ms-auto navbar-nav-scroll align-items-center">

            <li class="nav-item dropdown ms-auto">
              <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <img
                  src="{{request.user.get_image_url}}"
                  alt="{{request.user.username}}"
                  width="50px"
                  height="50px"
                  style="object-fit: cover; border-radius: 50%;"
                />
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarScrollingDropdown">
                <li><a class="dropdown-item" href="{% url 'users:ProfileView' %}">Manage Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'users:ChangePasswordView' %}">Change Password</a></li>
                <li><a class="dropdown-item" href="{% url 'users:LogoutView' %}">Logout</a></li>
              </ul>
            </li>
          </ul>
        {% else %}
          <ul class="navbar-nav my-2 my-lg-0 ms-auto navbar-nav-scroll">
            <div class="d-flex">
              <a href="{% url 'users:LoginView' %}" class="btn btn-secondary btn-sm mx-2">
                Login
              </a>
              <a href="{% url 'users:RegisterView' %}" class="btn btn-secondary btn-sm mx-2">
                Sign up
              </a>
            </div>
          </ul>
        {% endif %}

      </div>
    </div>
  </nav>

templates/users/change_password.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block ExtraCss %}
{% endblock ExtraCss %}

{% block content %}

<section class="card shadow-sm my-5 m-auto" style="max-width: 700px;">
  <div class="p-3">
      <form action="." method="post">
        {% csrf_token %}

        <h3>Change Password</h3>

        {{form|crispy}}

        <div style="text-align: end;">
          <button id="change" class="btn btn-primary" type="submit">Update</button>
        </div>
      </form>
  </div>
</section>

{% endblock content %}



{% block ExtraJs %}
{% endblock ExtraJs %}

templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="center-wrapper">
  <div class="card shadow-sm w-100 m-auto" style="max-width: 700px;">
    <form method="POST">
      {% csrf_token %}
      <legend class="border-bottom p-3">Log In!</legend>
      <div class="form-group px-3">
        {{ form|crispy }}
        <button class="btn btn-primary my-2" type="submit">Log In</button>
      </div>
      <div class="border-top p-3">
        <small class="text-muted">
          Need an account ? <a class="ml-2" href="{% url 'users:RegisterView' %}">Sign Up Now</a>
        </small>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

templates/users/logout.html
{% extends "base.html" %}
{% block content %}
  <div class="card shadow-sm my-5 m-auto" style="max-width: 700px;">
    <div class="p-3">
      <p class="fs-3">You have been logged out</p>
      <div class="border-top pt-3">
        <small class="text-muted">
          <a href="{% url 'users:LoginView' %}">Log In Again</a>
        </small>
      </div>
    </div>
  </div>

{% endblock content %}

templates/users/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block ExtraCss %}
{% endblock ExtraCss %}

{% block content %}

<section class="profile-information card shadow-sm my-5 m-auto" style="max-width: 700px;">
  <div class="p-3">
      <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}

          <div>
              <h3 class="title">
                Profile Information
              </h3>
          </div>

          <div class="lead">
              <p>Personal Details</p>
          </div>
          
            {{u_form|crispy}}

            <div class="d-flex justify-content-between align-items-center">
              <a href="{% url 'users:ChangePasswordView' %}">Change Password</a>
              <button id="change" class="btn btn-primary" type="submit">Update</button>
            </div>
      </form>
  </div>
</section>

{% endblock content %}



{% block ExtraJs %}
{% endblock ExtraJs %}

templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="center-wrapper">
  <div class="card shadow-sm w-100 m-auto" style="max-width: 700px;">
    <form method="POST">
      {% csrf_token %}
      <legend class="border-bottom p-3">Join today!</legend>
      <div class="form-group px-3">
        {{ form|crispy }}
        <button class="btn btn-primary my-2" type="submit">Sign Up</button>
      </div>
      <div class="border-top p-3">
        <small class="text-muted">
          Already have an account ? <a class="ml-2" href="{% url 'users:LoginView' %}">Sign In</a>
        </small>
      </div>
    </form>
  </div>
</div>

{% endblock content %}